sitegeo/sitegeo/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from geodesy import views
from geodesy.views import page_not_found
from sitegeo import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('geodesy.urls')),      # импорт urls из приложения(geodesy)
    path('users/', include('users.urls', namespace='users')),       # импорт urls из приложения(users)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# обработчик 404, с ссылкой на ф-ю представления. можно вызвать с помощью Http404()
handler404 = page_not_found


admin.site.site_header = "Станица администрирования"
admin.site.index_title = "Сайт Геодезические работы"

sitegeo/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('account/', views.account_user, name='account'),
    path('account/order/<int:order_id>/', views.order_user, name='order'),
    path('account/addorder/', views.addorder, name='addorder'),
    path('account/list_callback/', views.list_callback, name='list_callback'),

]

# path('logout/', LogoutView.as_view(), name='logout'),
# path('logout/', views.logout_user, name='logout'),

sitegeo/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="icon"  href="{% static 'geodesy/images/icon.png' %}">
    <link rel="stylesheet" href="{% static 'geodesy/css/styles.css' %}">
</head>
<body>
    <!-- главное меню -->
<div class="mainmenu">
    <ul>
        <li><a href="{% url 'home' %}">Главная</a></li>
        {% for m in mainmenu %}
        <li><a href="{% url m.url_name %}">{{m.title}}</a></li>
        {% endfor %}
    </ul>

    <ul class="last">
    {% if user.is_authenticated %}      <!-- если авторизован -->
    <li>
        <a href="{% url 'users:account' %}">{{ user.username }}</a>
        <form method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <button type="submit">Выйти</button>
        </form>
    </li>
    {% else %}
    <li><a href="{% url 'users:login' %}">Войти</a></li>
    {% endif %}
    </ul>
</div>
    <!-- /главное меню -->

<div class="content">
    {% block content %} {% endblock %}
</div>

<div class="footer">
    <p>Если у вас есть права, то они защищены!</p>
</div>

</body>
</html>

<!--
<a href="{% url 'users:logout' %}">Выйти</a>

<form method="post" action="{% url 'users:logout' %}">
    {% csrf_token %}
    <button type="submit">Выйти</button>
</form>
-->